name: Deploy Flagly Apps

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-flagly-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull recent code changes
        run: git pull origin master

      - name: Install dependencies
        run: npm install

      - name: Deploy Flagly UI
        uses: digitalocean/droplet-action@v2
        with:
          droplet_id: ${{ secrets.DIGITAL_OCEAN_DROPLET_ID }}
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          type: remote
          command: |
            cd /app
            pm2 stop app.js
            git pull origin master
            npm install
            pm2 start app.js
          
